- hosts: nginx
  become: yes  
  tasks:
    - name: Install Docker Python library
      apt:
        name: python3-docker
        state: present
        update_cache: yes

    - name: Login to Docker Hub
      docker_login:
        username: "datzofgk"
        password: "kmtls123@"

    - name: Deploy with Docker Compose
      shell: docker compose up -d
      args:
        chdir: /home/vsi/Docker
