- hosts: nginx
  tasks:
    - name: Copy docker-compose.yml to local host
      copy:
        src: docker-compose.yml
        dest: /home/vsi/Docker/docker-compose.yml

    - name: Deploy with Docker Compose
      shell: docker compose -f /home/vsi/Docker/docker-compose.yml up -d