- hosts: nginx
  become: yes
  become_method: sudo
  tasks:
    - name: Add vsi user to docker group
      user:
        name: vsi
        groups: docker
        append: yes
      become: yes
      become_method: sudo
      become_user: root

    - name: Login to Docker Hub
      docker_login:
        username: "datzofgk"
        password: "kmtls123@"

    - name: Deploy with Docker Compose
      shell: docker compose up -d
      args:
        chdir: /home/vsi/Docker
