- hosts: webservers
  tasks:
    - name: Deploy nginx
      community.docker.container:
        docker_container:
          name: nginx
          image: nginx-image
          state: started
          ports:
            - "80:80"
