---
- hosts: 10.10.3.70
  remote_user: vsi

  tasks:
    - name: Pull Docker Image
      command: docker pull datzofgk/nginx-image:v1

    - name: Run Docker Container
      command: docker run -d -p 80:80 datzofgk/nginx-image:v1

