- hosts: nginx
  tasks:
    - name: Copy docker-compose.yml to local host
      copy:
        src: docker-compose.yml
        dest: /home/vsi/Docker/docker-compose.yml

    - name: Deploy with Docker Compose
      shell: docker compose -f /home/vsi/Docker/docker-compose.yml up -d

    - name: Tag docker image with Nexus repo
      shell: |
        docker tag {{ image_name }} 10.10.3.67:1008/docker-hosted/{{ image_name }}:{{ image_tag }}
      args:
        executable: /bin/bash

    - name: Push image to Nexus repo
      shell: |
        docker push 10.10.3.67:1008/docker-hosted/{{ image_name }}:{{ image_tag }}
      args:
        executable: /bin/bash
