- hosts: nginx
  become: yes
  tasks:
    - name: Install docker-compose
      shell: |
        sudo curl -L https://github.com/docker/compose/releases/download/2.29.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
  
    - name: Deploy with Docker Compose
      shell: docker-compose up -d
      args:
        chdir: /home/vsi/Docker
