- hosts: nginx
  tasks:
    - name: Pull Docker image from Docker Hub
      shell: |
        docker pull datzofgk/nginx-image:{{ image_tag }}
      become: true

    - name: Copy docker-compose.yml to local host
      copy:
        src: docker-compose.yml
        dest: /home/vsi/Docker/docker-compose.yml

    - name: Deploy with Docker Compose
      shell: docker compose -f /home/vsi/Docker/docker-compose.yml up -d
      become: true
