- hosts: nginx
  become: yes
  tasks:
    - name: Download Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.18.2/docker-compose-linux-x86_64  # Thay thế URL bằng phiên bản và kiến trúc phù hợp
        dest: /usr/local/bin/docker-compose
        mode: '0755' 
        
    - name: Deploy with Docker Compose
      shell: docker-compose up -d
      args:
        chdir: /root/Docker/
