- hosts: all
  remote_user: vsi
  become: yes
  tasks:
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: nginx-image
        tag: v1

    - name: Deploy nginx container
      docker_container:
        name: nginx
        image: nginx-image:v1
        ports:
          - "80:80"
