- hosts: nginx
  become: yes
  tasks:
    - name: Install Docker Compose
      shell: |
        DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
        mkdir -p $DOCKER_CONFIG/cli-plugins
        curl -SL https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
        sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
        docker compose version
    
    - name: Deploy with Docker Compose
      shell: docker-compose up -d
      args:
        chdir: /root/Docker/
