- hosts: nginx
  tasks:
    - name: Copy docker-compose.yml to local host
      copy:
        src: docker-compose.yml
        dest: /home/vsi/Docker/docker-compose.yml

    - name: Deploy with Docker Compose
      shell: docker compose -f /home/vsi/Docker/docker-compose.yml up -d

    - name: Pull Docker image from Nexus
      shell: docker pull 10.10.3.67:1008/docker-hosted/datzofgk/nginx-image:{{ image_tag }}

    - name: Run Container
      shell: |
        docker run 2903:80 -d -p 10.10.3.67:1008/docker-hosted/datzofgk/nginx-image:{{ image_tag }}
