- hosts: nginx
  tasks:
    - name: Deploy with Docker Compose
      shell: docker compose up -d
      args:
        chdir: /home/vsi/Docker

    - name: Show Docker Compose logs
      shell: docker compose logs
