- hosts: vm2
  become: yes
  tasks:
    - name: Copy Docker Compose file to VM2
      copy:
        src: /root/Docker/docker-compose.yml
        dest: /home/vsi/docker-compose.yml

    - name: Deploy nginx container with Docker Compose
      shell: |
        docker-compose -f /home/vsi/docker-compose.yml up -d

