- hosts: nginx
  tasks:
    - name: Upgrade Docker Python library
      pip:
        name: docker
        state: latest

    - name: Login to Docker Hub
      docker_login:
        username: "datzofgk"
        password: "kmtls123@"

    - name: Deploy with Docker Compose
      shell: docker compose up -d
      args:
        chdir: /home/vsi/Docker
