- hosts: nginx
  tasks:
    - name: Install packages
      become: yes
      become_user: root
      pip:
        name:
          - requests
          - docker
      vars:
        ansible_python_interpreter: /usr/bin/python3
          
    - name: Pull Docker image from Docker Hub
      docker_image:
        name: datzofgk/nginx-image
        tag: v1
        source: pull

    - name: Run Docker container
      docker_container:
        name: nginx
        image: datzofgk/nginx-image:v1
        state: started
        ports:
          - "80:80"
