- hosts: nginx
  vars:
    docker_image: "datzofgk/nginx-image"
    image_tag: "{{ image_tag }}"
  tasks:
    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image }}:{{ image_tag }}"
        source: pull
      become: yes

    - name: Deploy with Docker Compose
      command: docker compose up -d
      args:
        chdir: /home/vsi/Docker
      become: yes
