---
- hosts: nginx
  tasks:
    - name: Pull Docker image from Docker Hub
      shell: docker pull datzofgk/nginx-image:{{ image_tag }}

    - name: Copy docker-compose.yml to local host
      copy:
        src: docker-compose.yml
        dest: /home/vsi/Docker/docker-compose.yml

    - name: Stop and remove the existing container
      shell: |
        docker-compose -f /home/vsi/Docker/docker-compose.yml down
      ignore_errors: true

    - name: Deploy with Docker Compose
      shell: |
        export IMAGE_TAG={{ image_tag }}
        docker compose -f /home/vsi/Docker/docker-compose.yml up -d

    - name: Pull Docker image from Nexus
      shell: |
        docker pull 10.10.3.67:1008/docker-hosted/
        datzofgk/nginx-image:{{ image_tag }}
